In [1]:
# from google.colab import drive
# drive.mount('/content/drive')

In [2]:

import pandas as pd
df = pd.read_csv('winequality-red.csv')
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [3]:
df.isna().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [4]:
df.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object

In [5]:
df['quality'].value_counts()

quality
5    681
6    638
7    199
4     53
8     18
3     10
Name: count, dtype: int64

In [6]:
X = df.iloc[:,:-1].values
X

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [7]:
y = df.iloc[:,-1]
y

0       5
1       5
2       5
3       6
4       5
       ..
1594    5
1595    6
1596    6
1597    5
1598    6
Name: quality, Length: 1599, dtype: int64

In [8]:
#3    -> 0
#4    1
#5    2
#6     3
#7     4
#8     5                                #is the wine quality. label encode it

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
encoded_y = le.fit_transform(y)

encoded_y

array([2, 2, 2, ..., 3, 2, 3], dtype=int64)

In [9]:
# convert 0 in y to 1 0 0 0 0 0
#         1         0 1 0 0 0 0 etc

from keras.utils import to_categorical
y_cat = to_categorical(encoded_y)
y_cat


array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       ...,
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y_cat,test_size=0.3,random_state=1)

In [11]:

from keras.models import Sequential
from keras.layers import Dense
model = Sequential()

In [12]:
# input layer
model.add(Dense(11,activation='relu'))    # units =11 bcoz 11 features

# 1st hidden layer
model.add(Dense(10,activation='relu'))

# 2nd hidden layer
model.add(Dense(20,activation='relu'))

# o/p layer . for binary classification dataset, 1 neuron is needed. we use sigmoid activation function

model.add(Dense(6,activation='softmax'))    # for o/p layer either sigmoid/softmax is used
#

In [13]:
model.compile(optimizer='adam', loss="categorical_crossentropy", metrics=['accuracy'])    # optimizer for updating weight , loss= diff of actual n predicted value, specify which metric performance to be improved by updating weight

In [14]:
model.fit(X_train,y_train, epochs=100, batch_size=10)  # epoch means how many times model shud learn, batch size is to split data for learning as batches


Epoch 1/100
112/112 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.3862 - loss: 4.7022
Epoch 2/100
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4762 - loss: 1.2989
Epoch 3/100
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4923 - loss: 1.3083
Epoch 4/100
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5019 - loss: 1.2293
Epoch 5/100
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4914 - loss: 1.1731
Epoch 6/100
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4950 - loss: 1.1114
Epoch 7/100
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4950 - loss: 1.1328
Epoch 8/100
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5490 - loss: 1.1225
Epoch 9/100
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4731 - loss: 1.1937
Epoch 10/100
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4886 - loss: 1.1620
Epoch 11/100
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5128 - loss: 1.1436
Epoch 12/100
112/112 ━━━━━━━━━━━━━━━━━━━━

In [15]:
model.summary()    # 4 is no: of i/p, 5 is no: of neurons(4 + 1 bias). 4*5 =20

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 10)             │           120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 20)             │           220 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 6)              │           126 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,796 (7.02 KB)

 Trainable params: 598 (2.34 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 1,198 (4.68 KB)

binary clasification problems can be handled using softmax algm, convert y to categorical data. change 0 to 0 0,        1 to 0 1

In [16]:
y_pred = model.predict(X_test)
y_pred

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 


array([[1.0623942e-03, 1.0919070e-02, 4.2495859e-01, 5.1750851e-01,
        4.3757923e-02, 1.7935871e-03],
       [1.4470408e-03, 1.1712377e-02, 6.3338923e-01, 3.4137893e-01,
        1.1729378e-02, 3.4307421e-04],
       [4.8339478e-04, 8.9587886e-03, 1.5149195e-01, 4.7487974e-01,
        3.3367556e-01, 3.0510627e-02],
       ...,
       [4.1273944e-02, 9.4675966e-02, 6.3683432e-01, 2.1927899e-01,
        7.5912741e-03, 3.4547932e-04],
       [1.2809162e-03, 1.7409757e-02, 3.9869326e-01, 5.4567379e-01,
        3.5519708e-02, 1.4225884e-03],
       [2.1657711e-03, 2.6595186e-02, 2.5960791e-01, 5.0917935e-01,
        1.8335244e-01, 1.9099388e-02]], dtype=float32)

In [17]:
loss,accuracy = model.evaluate(X_test,y_test)
print('loss ',loss)
print('accuracy ',accuracy)

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6486 - loss: 0.8511  
loss  0.940759539604187
accuracy  0.6291666626930237


In [20]:
import numpy as np

# Input data as a NumPy array
x_new = np.array([[7.4, 0.700, 0.00, 1.9, 0.076, 11.0, 34.0, 0.99780, 3.51, 0.56, 9.4]])

# Predict using the model
y_new = model.predict(x_new)
print(y_new)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step
[[1.2262860e-02 4.4680621e-02 7.0494878e-01 2.3584326e-01 2.2205943e-03
  4.3880391e-05]]


In [21]:
# loc to find max value in y_new

ind = y_new.argmax(axis=1)
ind.item()  # returns index value

2

In [22]:
cls = le.inverse_transform(ind)
cls.item()   # quality 5

5

In [23]:
y_pred = model.predict(X_test)
y_pred

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step 


array([[1.0623942e-03, 1.0919070e-02, 4.2495859e-01, 5.1750851e-01,
        4.3757923e-02, 1.7935871e-03],
       [1.4470408e-03, 1.1712377e-02, 6.3338923e-01, 3.4137893e-01,
        1.1729378e-02, 3.4307421e-04],
       [4.8339478e-04, 8.9587886e-03, 1.5149195e-01, 4.7487974e-01,
        3.3367556e-01, 3.0510627e-02],
       ...,
       [4.1273944e-02, 9.4675966e-02, 6.3683432e-01, 2.1927899e-01,
        7.5912741e-03, 3.4547932e-04],
       [1.2809162e-03, 1.7409757e-02, 3.9869326e-01, 5.4567379e-01,
        3.5519708e-02, 1.4225884e-03],
       [2.1657711e-03, 2.6595186e-02, 2.5960791e-01, 5.0917935e-01,
        1.8335244e-01, 1.9099388e-02]], dtype=float32)

In [24]:
y_test

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       ...,
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

y_test and y_pred cant be compared, so

In [25]:
y_pred = model.predict(X_test)
y_pred.argmax(axis=1)

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 


array([3, 2, 3, 3, 4, 3, 3, 2, 3, 2, 3, 2, 2, 4, 3, 2, 3, 2, 3, 2, 3, 3,
       2, 3, 2, 3, 3, 3, 2, 2, 2, 4, 2, 3, 2, 3, 2, 2, 3, 2, 3, 2, 2, 3,
       2, 3, 2, 2, 2, 3, 2, 2, 3, 2, 2, 3, 3, 3, 3, 2, 3, 2, 2, 2, 2, 2,
       4, 2, 3, 4, 2, 3, 3, 3, 2, 3, 3, 2, 2, 3, 3, 2, 2, 3, 3, 2, 2, 3,
       2, 3, 2, 3, 2, 3, 3, 2, 3, 2, 2, 3, 3, 2, 2, 2, 2, 2, 3, 2, 3, 2,
       4, 2, 3, 3, 2, 4, 2, 2, 2, 2, 2, 4, 3, 2, 2, 3, 3, 2, 3, 3, 3, 2,
       3, 2, 3, 3, 2, 4, 2, 2, 2, 2, 3, 2, 3, 3, 3, 2, 3, 3, 2, 3, 2, 2,
       3, 3, 3, 3, 3, 2, 3, 3, 2, 2, 3, 3, 3, 2, 2, 3, 2, 3, 2, 2, 4, 2,
       2, 2, 2, 2, 3, 3, 3, 2, 3, 3, 3, 2, 2, 2, 2, 3, 2, 2, 3, 2, 3, 2,
       3, 2, 3, 3, 3, 2, 4, 3, 2, 2, 3, 3, 2, 3, 2, 3, 2, 2, 2, 2, 3, 2,
       3, 3, 2, 2, 3, 3, 2, 3, 4, 2, 2, 2, 3, 3, 3, 2, 3, 2, 2, 2, 3, 3,
       3, 2, 3, 4, 3, 2, 2, 2, 2, 2, 3, 3, 3, 2, 2, 2, 2, 3, 3, 2, 2, 2,
       2, 3, 3, 2, 2, 3, 2, 3, 2, 4, 2, 3, 2, 3, 2, 2, 4, 2, 3, 2, 2, 3,
       2, 2, 2, 3, 2, 3, 2, 2, 3, 3, 2, 3, 2, 2, 3,

In [26]:
y_test.argmax(axis=1)

array([2, 3, 3, 3, 3, 3, 3, 2, 2, 2, 3, 3, 3, 3, 3, 2, 3, 2, 2, 2, 3, 3,
       2, 3, 3, 3, 3, 3, 3, 4, 3, 3, 2, 3, 2, 3, 2, 4, 3, 2, 3, 2, 2, 3,
       2, 3, 2, 2, 2, 3, 2, 1, 4, 2, 2, 3, 3, 3, 2, 2, 2, 3, 2, 3, 2, 3,
       4, 3, 3, 3, 2, 3, 3, 3, 2, 2, 3, 3, 2, 3, 2, 2, 2, 3, 2, 2, 2, 4,
       2, 3, 2, 4, 2, 3, 2, 2, 3, 2, 0, 3, 2, 2, 2, 2, 2, 2, 3, 3, 2, 3,
       4, 2, 3, 3, 2, 4, 2, 2, 2, 2, 1, 4, 4, 2, 2, 2, 3, 2, 4, 4, 3, 2,
       4, 2, 3, 4, 2, 4, 3, 3, 2, 3, 3, 2, 3, 3, 3, 2, 3, 3, 3, 3, 2, 3,
       2, 4, 2, 3, 3, 3, 5, 3, 2, 2, 3, 3, 1, 2, 2, 3, 3, 3, 1, 4, 2, 3,
       2, 2, 2, 2, 3, 3, 2, 3, 3, 3, 4, 3, 1, 3, 2, 3, 3, 2, 3, 2, 1, 2,
       3, 2, 4, 2, 4, 2, 4, 3, 2, 2, 3, 2, 2, 4, 2, 3, 2, 3, 2, 2, 4, 3,
       2, 3, 2, 2, 3, 2, 1, 4, 4, 4, 3, 3, 4, 3, 3, 3, 3, 3, 2, 1, 3, 2,
       4, 3, 3, 5, 3, 2, 2, 2, 2, 1, 3, 3, 3, 2, 2, 1, 2, 2, 3, 2, 2, 2,
       1, 3, 2, 2, 3, 3, 2, 3, 2, 3, 3, 2, 2, 3, 2, 2, 3, 1, 1, 2, 3, 2,
       3, 2, 2, 2, 3, 3, 3, 2, 3, 4, 2, 2, 2, 2, 3,

In [27]:
from sklearn.metrics import classification_report
print(classification_report(y_test.argmax(axis=1),y_pred.argmax(axis=1)))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.00      0.00      0.00        21
           2       0.66      0.77      0.71       207
           3       0.60      0.66      0.63       195
           4       0.56      0.27      0.36        52
           5       0.00      0.00      0.00         3

    accuracy                           0.63       480
   macro avg       0.30      0.28      0.28       480
weighted avg       0.59      0.63      0.60       480



c:\Users\aiswa\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\aiswa\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\aiswa\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average,